-- MySQL Script generated by MySQL Workbench
-- Tue Aug 29 10:28:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `daw-aluno15-2017` DEFAULT CHARACTER SET utf8 ;
USE `daw-aluno15-2017` ;

-- -----------------------------------------------------
-- Table `daw-aluno15-2017`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daw-aluno15-2017`.`cargos` (
  `idcargos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `salario` INT NOT NULL,
  PRIMARY KEY (`idcargos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw-aluno15-2017`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daw-aluno15-2017`.`Funcionarios` (
  `idfuncionario` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `CPF` INT NOT NULL,
  `cargos_idcargos` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  INDEX `fk_Funcionarios_cargos_idx` (`cargos_idcargos` ASC),
  CONSTRAINT `fk_Funcionarios_cargos`
    FOREIGN KEY (`cargos_idcargos`)
    REFERENCES `daw-aluno15-2017`.`cargos` (`idcargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Impressoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daw-aluno15-2017`.`Impressoras` (
  `idimpressora` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idimpressora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw-aluno15-2017`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daw-aluno15-2017`.`clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` INT NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw-aluno15-2017`.`Atendimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daw-aluno15-2017`.`Atendimentos` (
  `idatendimento` INT NOT NULL AUTO_INCREMENT,
  `num_paginas` INT NOT NULL,
  `valor` INT NOT NULL,
  `data` DATE NOT NULL,
  `Funcionarios_idfuncionario` INT NOT NULL,
  `Impressoras_idimpressora` INT NOT NULL,
  `clientes_idcliente` INT NOT NULL,
  PRIMARY KEY (`idatendimento`),
  INDEX `fk_Atendimentos_Funcionarios1_idx` (`Funcionarios_idfuncionario` ASC),
  INDEX `fk_Atendimentos_Impressoras1_idx` (`Impressoras_idimpressora` ASC),
  INDEX `fk_Atendimentos_clientes1_idx` (`clientes_idcliente` ASC),
  CONSTRAINT `fk_Atendimentos_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idfuncionario`)
    REFERENCES `daw-aluno15-2017`.`Funcionarios` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimentos_Impressoras1`
    FOREIGN KEY (`Impressoras_idimpressora`)
    REFERENCES `daw-aluno15-2017`.`Impressoras` (`idimpressora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimentos_clientes1`
    FOREIGN KEY (`clientes_idcliente`)
    REFERENCES `daw-aluno15-2017`.`clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
