-- MySQL Script generated by MySQL Workbench
-- Qui 23 Ago 2018 09:44:40 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 2016952932
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 2016952932
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2016952932` DEFAULT CHARACTER SET utf8 ;
USE `2016952932` ;

-- -----------------------------------------------------
-- Table `2016952932`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2016952932`.`Item` (
  `Codigo` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Valor` FLOAT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2016952932`.`Estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2016952932`.`Estabelecimento` (
  `CNPJ` INT NOT NULL,
  `Endereço` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Item_Codigo` INT NOT NULL,
  PRIMARY KEY (`CNPJ`),
  INDEX `fk_Estabelecimento_Item1_idx` (`Item_Codigo` ASC),
  CONSTRAINT `fk_Estabelecimento_Item1`
    FOREIGN KEY (`Item_Codigo`)
    REFERENCES `2016952932`.`Item` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2016952932`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2016952932`.`Pedido` (
  `Codigo` INT NOT NULL,
  `Hora` DATETIME NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2016952932`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2016952932`.`Cliente` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Telefone` INT NULL,
  `Pedido_Codigo` INT NOT NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_Cliente_Pedido1_idx` (`Pedido_Codigo` ASC),
  CONSTRAINT `fk_Cliente_Pedido1`
    FOREIGN KEY (`Pedido_Codigo`)
    REFERENCES `2016952932`.`Pedido` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2016952932`.`Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2016952932`.`Motorista` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Pedido_Codigo` INT NOT NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_Motorista_Pedido1_idx` (`Pedido_Codigo` ASC),
  CONSTRAINT `fk_Motorista_Pedido1`
    FOREIGN KEY (`Pedido_Codigo`)
    REFERENCES `2016952932`.`Pedido` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2016952932`.`Incluso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2016952932`.`Incluso` (
  `Item_Codigo` INT NOT NULL,
  `Pedido_Codigo` INT NOT NULL,
  PRIMARY KEY (`Item_Codigo`, `Pedido_Codigo`),
  INDEX `fk_Item_has_Pedido_Pedido1_idx` (`Pedido_Codigo` ASC),
  INDEX `fk_Item_has_Pedido_Item1_idx` (`Item_Codigo` ASC),
  CONSTRAINT `fk_Item_has_Pedido_Item1`
    FOREIGN KEY (`Item_Codigo`)
    REFERENCES `2016952932`.`Item` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_Codigo`)
    REFERENCES `2016952932`.`Pedido` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
