#CRIANDO AS TABELAS BONITINHAS COM A ID PRIMARY KEY

CREATE TABLE Cargos(
ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
Nome VARCHAR( 100 ) NOT NULL,
Salario INT NOT NULL
);

CREATE TABLE Clientes(
ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
Nome VARCHAR( 100 ) NOT NULL,
CPF INT NOT NULL
);

CREATE TABLE Impressoras(
ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
Nome VARCHAR( 100 ) NOT NULL,
Marca VARCHAR( 100 ) NOT NULL
);

CREATE TABLE Funcionarios(
ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
Nome VARCHAR( 100 ) NOT NULL,
CPF INT NOT NULL
);

CREATE TABLE Atendimentos(
Num_paginas INT NOT NULL,
Valor INT NOT NULL,
Data DATE NOT NULL,
ClienteID INT NOT NULL,
FuncionarioID INT NOT NULL,
ImpressoraID INT NOT NULL
);

#ADICIONANDO AS LIGACOES DE FOREIGN KEY N-1 PARA OS ATENDIMENTOS

ALTER TABLE Atendimentos
ADD CONSTRAINT fk_Atendimento_Impressora FOREIGN KEY (ImpressoraID) REFERENCES Impressoras(ID),
ADD CONSTRAINT fk_Atendimento_Funcionario FOREIGN KEY (FuncionarioID) REFERENCES Funcionarios(ID),
ADD CONSTRAINT fk_Atendimento_Cliente FOREIGN KEY (ClienteID) REFERENCES Clientes(ID);

#ADICIONANDO AS LIGACOES DE FOREIGN KEY 1-N PARA OS FUNCIONARIOS

ALTER TABLE Funcionarios
ADD CargoID INT NOT NULL,
ADD CONSTRAINT fk_Funcionario_Cargo FOREIGN KEY (CargoID) REFERENCES Cargos(ID);

#ADICIONANDO AS TABELAS DE FOREIGN KEY 1-N DAS IMPRESSORAS PARA OS ATENDIMENTOS

CREATE TABLE Impressoras_Atendimentos(
ImpressoraID INT NOT NULL,
AtendimentoID INT NOT NULL,
CONSTRAINT fk_ii FOREIGN KEY (ImpressoraID) REFERENCES Impressoras(ID),
CONSTRAINT fk_aa FOREIGN KEY (AtendimentoID) REFERENCES Atendimentos(ID));

#ADICIONANDO AS TABELAS DE FOREIGN KEY 1-N DOS FUNCIONARIOS PARA OS ATENDIMENTOS

CREATE TABLE Funcionarios_Atendimentos(
FuncionarioID INT NOT NULL,
AtendimentoID INT NOT NULL,
CONSTRAINT fk_ff FOREIGN KEY (FuncionarioID) REFERENCES Funcionarios(ID),
CONSTRAINT fk_aa FOREIGN KEY (AtendimentoID) REFERENCES Atendimentos(ID));

#ADICIONANDO AS TABELAS DE FOREIGN KEY 1-N DOS CLIENTES PARA OS ATENDIMENTOS

CREATE TABLE Clientes_Atendimentos(
ClienteID INT NOT NULL,
AtendimentoID INT NOT NULL,
CONSTRAINT fk_cc FOREIGN KEY (ClienteID) REFERENCES Clientes(ID),
CONSTRAINT fk_aa FOREIGN KEY (AtendimentoID) REFERENCES Atendimentos(ID));